### ISSUE TITLE
Don't use deprecated SPDX identifiers

### ISSUE THREAD

**Issue by isuruf** [marcelotrevisani/grayskull#106]
For eg: `GPL-2.0` is deprecated, but there's a test

`get_short_license_id("GPL 2.0") == "GPL-2.0"`

**Comment by marcelotrevisani** [comment]
That is true indeed. To be honest, I didn't know that was deprecated. ``grayskull`` is getting the spdx from ``opensource.org``, I will change it to get all ``spdx`` from ``spdx.org`` then, in that way I can check if the license was deprecated or not.

Thanks for reporting it! :)

**Comment by marcelotrevisani** [comment]
For example, on ``opensource.org`` they are still pointing that the ``spdx`` for ``GPL 2.0`` is ``GPL-2.0``
https://opensource.org/licenses/GPL-2.0

It seems they are not the best source to rely on license information
:grimacing:

**Comment by marcelotrevisani** [comment]
Solved with #107 and I generated version ``0.3.0`` for that
