### ISSUE TITLE
Track different pkg names on PyPI and conda-forge

### ISSUE THREAD

**Issue by marcelotrevisani** [marcelotrevisani/grayskull#118]
Track different pkg names on PyPI and conda-forge

For example:
- ``python-opencv`` is just ``opencv`` on ``conda-forge``
- ``tables`` on PyPI is ``pytables`` on ``conda-forge`` (and there is a package on ``pypi`` with the name ``pytables`` which is not the same ``pytables`` on ``conda-forge``)

cc: @ocefpaf

**Comment by ocefpaf** [comment]
It is not the same thing but it can help. We have a list of [conda-forge package names vs import names here](https://github.com/ericdill/depfinder/blob/master/depfinder/pkg_data/pkg_data.yml). I would be nice to have that kind of information in a format that we can use in other places.

**Comment by marcelotrevisani** [comment]
There is another one which might be problematic which is ``pyqt``
it is just ``pyqt`` on ``conda-forge`` but on ``pypi`` it is ``pyqt4`` or ``pyqt5``
