### ISSUE TITLE
Keep license file name from source distribution

### ISSUE THREAD

**Issue by synapticarbors** [marcelotrevisani/grayskull#119]
I noticed when creating a recipe that the upstream repo named the license file `LICENSE.md` and grayskull made a copy called `LICENSE`. It might be useful to match the naming convention in the upstream repo so that when the license file is eventually included in the upstream repo, there is no need to make changes to the `meta.yaml` in addition to deleting the manually packaged copy.

**Comment by marcelotrevisani** [comment]
Thanks for opening this issue! 

Sure, I will take a look at it.
Do you know a package on pypi which this is happening, please? So I can easily reproduce it

**Comment by synapticarbors** [comment]
The pypi package is `respx`

**Comment by marcelotrevisani** [comment]
> The pypi package is `respx`

Thanks a lot! I will try to reproduce it

**Comment by marcelotrevisani** [comment]
Yeap, indeed it is not creating the file with the same name as in the repository. I will add this in a couple of days
Thanks for reporting

**Comment by synapticarbors** [comment]
A few other unrelated questions from using `grayskull` for the first time (and let me know if you'd rather me raise these elsewhere):

- Is there any way to get grayskull to pull the `dev_url` from pypi, or figure out a better `home` than the pypi url? For example, looking for the `url` in `setup` (https://github.com/lundberg/respx/blob/master/setup.py#L14)

- Is there an explanation of what `pip check` is doing in the context of a package built with `conda`? I've seen this coming up in a few places and I don't feel like I really understand what the caveats are of using this, if any.

**Comment by marcelotrevisani** [comment]
>     * Is there any way to get grayskull to pull the `dev_url` from pypi, or figure out a better `home` than the pypi url? For example, looking for the `url` in `setup` (https://github.com/lundberg/respx/blob/master/setup.py#L14)

I need to check it, but I think that ``grayskull`` tries to get it the ``dev_url`` first from the metadata, if it does not exist it uses the ``pypi``. But I need to check it


>     * Is there an explanation of what `pip check` is doing in the context of a package built with `conda`? I've seen this coming up in a few places and I don't feel like I really understand what the caveats are of using this, if any.
``pip check`` test if the whole dependencies of that package are installed, but sometimes it does not work well, but at least it is a second validation if it fails the user can just remove it. I think @ocefpaf can give you a better explanation about it
