### ISSUE TITLE
Matplotlib-base rather than matplotlib as default

### ISSUE THREAD

**Issue by CJ-Wright** [marcelotrevisani/grayskull#126]
For most packages we can use `matplotlib-base` rather than `matplotlib`.

**Comment by marcelotrevisani** [comment]
Thanks for letting me know!
I am developing a feature for ``grayskull`` to track different names of packages ``PyPI`` and ``conda-forge`` (that can be easily expanded when we add support for other repos), after that it will be possible. I just need to keep in mind to add ``matplotlib`` to that as well :)


Related to https://github.com/marcelotrevisani/grayskull/issues/118

**Comment by marcelotrevisani** [comment]
@CJ-Wright I generated the version [0.5.0](https://github.com/marcelotrevisani/grayskull/releases/tag/0.5.0) for grayskull which fix it
Any other problem with packages which we should replace in the recipe, please let me know! :)
