### ISSUE TITLE
Improve test import section

### ISSUE THREAD

**Issue by marcelotrevisani** [marcelotrevisani/grayskull#143]
as reported by @ocefpaf it would be nice to remove the fallback to the package name in case of missing ``packages`` and put a placeholder instead
we also need to check for the ``py_modules``, description about it can be found here: https://docs.python.org/3/distutils/examples.html

package to test with: ``python-markdown-math``

**Comment by ocefpaf** [comment]
One day I'll learn how to use GitHub properly and stop bugging you directly :stuck_out_tongue_winking_eye:

**Comment by marcelotrevisani** [comment]
hahaha, no worries, you can continue to report that like
I just like to create the issue to not forget about the problem :D
