### ISSUE TITLE
pypi _injection_distutils changes folders without protections

### ISSUE THREAD

**Issue by CJ-Wright** [marcelotrevisani/grayskull#146]
If the code inside `_injection_distutils` fails then it leaves the code in an undetermined directory which can cause code calling this to fail. Would it be possible to use [`indir`](https://xon.sh/api/lib/os.html?highlight=indir#xonsh.lib.os.indir)

**Comment by marcelotrevisani** [comment]
The ``indir`` is not necessary at all, I already have a context manager for the injection just need to change the folder

**Comment by marcelotrevisani** [comment]
Do you have already a case scenario which this thing is happening? So I can reproduce it
because it just needs to add a ``finally`` clause in a ```try`` and it should be fine and cover it
However, I cannot reproduce it

Thanks for reporting it! :)

**Comment by CJ-Wright** [comment]
you might try giving pyproj a shot https://app.circleci.com/pipelines/github/regro/circle_worker/8150/workflows/a6d30435-0fa7-441c-9910-72c60ceb9968/jobs/23948

**Comment by CJ-Wright** [comment]
Actually the issue seems to be that `pyproj` has multiple `sys.exit` in its setup.py. I think if you `except BaseException` rather than `except Exception` it will be caught.

**Comment by CJ-Wright** [comment]
Or you can explicitly `except SystemExit`

**Comment by marcelotrevisani** [comment]
Yeap! that was what I was checking, I can change that and just to ``except`` without the ``Exception``
It should catch all exceptions

**Comment by marcelotrevisani** [comment]
nice, I will create some tests and going to change that
thanks for it! :)

**Comment by marcelotrevisani** [comment]
#147 should fix this corner case, thanks a lot for reporting it! :tada: :tada: :tada:

**Comment by CJ-Wright** [comment]
sure, would it be possible to cut a release after that goes in?

**Comment by marcelotrevisani** [comment]
> sure, would it be possible to cut a release after that goes in?

Yes, sure, no problem

**Comment by CJ-Wright** [comment]
thank you!

**Comment by marcelotrevisani** [comment]
> thank you!

It is already on pypi the new version ``0.7.1`` and it should be on ``conda-forge`` in a couple of minutes
Any problem please let me know
Thanks again! :smile:
