### ISSUE TITLE
greyskull

### ISSUE THREAD

**Issue by asmeurer** [marcelotrevisani/grayskull#156]
I can never remember how to spell the name of this tool, and I have about a 50% chance of getting it right each time. I would suggest adding a `greyskull` shortcut command as well as a shortcut conda package.

**Comment by marcelotrevisani** [comment]
Yes, sure, I think it is not a problem at all to add a new entry point for ``greyskull``.
Thanks for the suggestion! :)

**Comment by marcelotrevisani** [comment]
@asmeurer I generated version ``0.7.3`` of ``grayskull`` with this new entry point ``greyskull``
So you will be able to call it ``grayskull`` or ``greyskull``. I hope it helps!

**Comment by marcelotrevisani** [comment]
https://github.com/marcelotrevisani/grayskull-feedstock/#current-release-info
