### ISSUE TITLE
Version in webapp isn't wrapped in quotes

### ISSUE THREAD

**Issue by rwhitt2049** [marcelotrevisani/grayskull#159]
When creating a recipe from the webapp, the version isn't wrapped in quotes which causes jinja rendering errors when you run `conda build`

For example if you do pytest, version 5.3.4, the webapp gives the recipe

```yaml
{% set name = "pytest" %}
{% set version = 5.3.4 %}
```

but it needs to be the below to render properly

```yaml
{% set name = "pytest" %}
{% set version = "5.3.4" %}

```

**Comment by marcelotrevisani** [comment]
I will take a look on that, I didn't pay attention to that to be honest.
Thanks for reporting it! I will fix it in a couple of days

**Comment by marcelotrevisani** [comment]
Fixed! Sorry for the delay, I have been a bit busy these days :/
