### ISSUE TITLE
Add option to drop sdist package in a specific folder

### ISSUE THREAD

**Issue by marcelotrevisani** [marcelotrevisani/grayskull#80]
Add option (maybe ``--sdist-download-folder``) to drop sdist package in a specific folder

cc: @ocefpaf

**Comment by ocefpaf** [comment]
I was think on something along the lines:

``grayskull pypi <pkgname> --download`` and just drop the sdist with the recipe.

The user can inspect it, fix the recipe, and remove it.

(A long ago we even considered committing the sdist alongside the recipe for reproducilibity, maybe we'll get back to that idea.)

**Comment by marcelotrevisani** [comment]
For me, that is good! No objections from my side
if you think it is interesting, I can also drop the ``json`` from ``pypi`` with the whole metadata in the same folder

**Comment by ocefpaf** [comment]
> For me, that is good! No objections from my side
> if you think it is interesting, I can also drop the `json` from `pypi` with the whole metadata in the same folder

Makes sense to expose that too! It will make it easier spot bad metadata and fix it.
