### ISSUE TITLE
exclude modules in the same folder as setup.py from host

### ISSUE THREAD

**Issue by marcelotrevisani** [marcelotrevisani/grayskull#92]
Grayskull needs to exclude modules from the same level as ``setup.py``
one of the problems is because everything in the same level as ``setup.py`` will be seen by python as a module, any new ``.py`` file or any folder with a ``__init__.py``

Recipes to test with this problem:
 * ``bokeh`` : adding ``_setup_support`` to ``host`` section
 *  ``ipycytoscape`` : adding ``setupbase`` to ``host`` section

thanks @ocefpaf for reporting it

**Comment by ocefpaf** [comment]
Or we could force people to move away for `setup.py` and adopt modern packaging techniques ;-p

**Comment by marcelotrevisani** [comment]
> Or we could force people to move away for `setup.py` and adopt modern packaging techniques ;-p

that is ideal! :smile:
