### ISSUE TITLE
Issue found when testing with a few recipes

### ISSUE THREAD

**Issue by ocefpaf** [marcelotrevisani/grayskull#93]
- djangorestframework-xml had the wrong import test and license
- nbdime also got the wrong license

Are you getting the import test from the package name or the modules list?

**Comment by marcelotrevisani** [comment]
Thanks! I will look on it!

**Comment by marcelotrevisani** [comment]
>     * djangorestframework-xml had the wrong import test and license
> 
>     * nbdime also got the wrong license
> 
> 
> Are you getting the import test from the package name or the modules list?

I forgot to answer you, sorry
But I was getting from the package name, which is wrong, my mistake, sorry
I will fix it with #94
