### ISSUE TITLE
Missed mypy entrypoints

### ISSUE THREAD

**Issue by ocefpaf** [marcelotrevisani/grayskull#97]
Mypy has 3 entry-points and the new recipe generated with grayskull missed those. Not sure why, investigating. (I used version 0.2.2.)

**Comment by marcelotrevisani** [comment]
that is weird indeed.
I think it is because of the ``mypyc``
```python
from mypyc.build import mypycify
```

However, it should try to build and get the metadata, I will investigate it.
I think I might know what is happening
